"""
csv-to-iceberg Glue job (Visual ETL generated)
Glue job generated using AWS Glue Visual ETL.

Purpose:
- Read CSV files from S3 source layer
- Select required fields
- Write data into Apache Iceberg table
- Register metadata in AWS Glue Data Catalog

Note:
This script is generated by Visual ETL and version-controlled
for transparency and reproducibility.
"""

import sys
from awsglue.transforms import *
from awsglue.utils import getResolvedOptions
from pyspark.context import SparkContext
from awsglue.context import GlueContext
from awsglue.job import Job
from awsgluedq.transforms import EvaluateDataQuality

args = getResolvedOptions(sys.argv, ['JOB_NAME'])
sc = SparkContext()
glueContext = GlueContext(sc)
spark = glueContext.spark_session
job = Job(glueContext)
job.init(args['JOB_NAME'], args)

# Default ruleset used by all target nodes with data quality enabled
DEFAULT_DATA_QUALITY_RULESET = """
    Rules = [
        ColumnCount > 0
    ]
"""

# Script generated for node Amazon S3 - Source
AmazonS3Source_node1770427691235 = glueContext.create_dynamic_frame.from_options(format_options={"quoteChar": "\"", "withHeader": True, "separator": ","}, connection_type="s3", format="csv", connection_options={"paths": ["s3://epam-demo-source/source/"], "recurse": True}, transformation_ctx="AmazonS3Source_node1770427691235")

# Script generated for node Select Fields
SelectFields_node1770430735636 = SelectFields.apply(frame=AmazonS3Source_node1770427691235, paths=["order_id", "order_date", "order_customer_id", "order_status"], transformation_ctx="SelectFields_node1770430735636")

# Script generated for node Amazon S3 - Target
EvaluateDataQuality().process_rows(frame=SelectFields_node1770430735636, ruleset=DEFAULT_DATA_QUALITY_RULESET, publishing_options={"dataQualityEvaluationContext": "EvaluateDataQuality_node1770427680170", "enableDataQualityResultsPublishing": True}, additional_options={"dataQualityResultsPublishing.strategy": "BEST_EFFORT", "observations.scope": "ALL"})
additional_options = {}
tables_collection = spark.catalog.listTables("onboarding_db")
table_names_in_db = [table.name for table in tables_collection]
table_exists = "orders" in table_names_in_db
if table_exists:
    AmazonS3Target_node1770428586486_df = SelectFields_node1770430735636.toDF()
    AmazonS3Target_node1770428586486_df        .writeTo("glue_catalog.onboarding_db.orders") \
        .tableProperty("format-version", "2") \
        .tableProperty("location", "s3://epam-demo-sink/sink/onboarding_db/orders") \
        .tableProperty("write.parquet.compression-codec", "uncompressed") \
        .options(**additional_options) \
.append()
else:
    AmazonS3Target_node1770428586486_df = SelectFields_node1770430735636.toDF()
    AmazonS3Target_node1770428586486_df        .writeTo("glue_catalog.onboarding_db.orders") \
        .tableProperty("format-version", "2") \
        .tableProperty("location", "s3://epam-demo-sink/sink/onboarding_db/orders") \
        .tableProperty("write.parquet.compression-codec", "uncompressed") \
        .options(**additional_options) \
.create()

job.commit()